apps/gallery/urls.py
from django.urls import path

from . import views


app_name = 'gallery'
urlpatterns = [
    path('', views.LatestView.as_view(), name='latest'),
    path('<int:pk>/', views.DetailView.as_view(), name='post'),
    path('posts/', views.PostsView.as_view(), name='posts'),
    path('random/', views.RandomView.as_view(), name='random'),
]

loebefisk/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('apps.gallery.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

apps/gallery/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from tinymce.models import HTMLField

class Post(models.Model):
    """
    A post with a title, an author, a published date and an image.
    """
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    image = models.ImageField(null=True, blank=True, upload_to='images/%Y/%m/%d/')
    text = HTMLField(blank=True) 

    def __str__(self):
        return self.title + ' by ' + self.author
    
    @classmethod
    def get_published_posts(cls):
        """
        Return a QuerySet of all published posts.
        """
        return cls.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')

    def get_absolute_url(self):
        """
        Return the absolute url of this post.
        """
        return reverse('gallery:post', kwargs={'pk': self.pk})

    def get_previous(self):
        """
        Return the post published right before this post. If no such post
        exists, None is returned.
        """
        try:
            return Post.get_published_posts().filter(pub_date__lt=self.pub_date).order_by('-pub_date')[0]
        except IndexError:
            return None

    def get_next(self):
        """
        Return the post published right after this post. If no such post
        exists, None is returned.
        """
        try:
            return Post.get_published_posts().filter(pub_date__gt=self.pub_date).order_by('pub_date')[0]
        except IndexError:
            return None

    def is_first(self):
        posts = Post.get_published_posts()
        return posts[0] == self

    def is_last(self):
        posts = Post.get_published_posts()
        return posts[len(posts)-1] == self

apps/gallery/views.py
from django.shortcuts import render
from django.views import generic
from django.utils import timezone
from django.http import HttpResponseRedirect, Http404

import random

from .models import Post

class PostView(generic.DetailView):
    """
    A view for a single post.
    """
    model = Post
    template_name = 'gallery/post.html'

class LatestView(generic.View):
    """
    A view that shows the most recently published post.
    """
    def get_object(self):
        """
        Return the most recently published post.
        """
        return Post.get_published_posts()[0]

    def get(self, request):
        """
        Redirect to the url of the most recently published post.
        """
        return HttpResponseRedirect(self.get_object().get_absolute_url())

class RandomView(generic.View):
    """
    A view that shows the most recently published post.
    """
    def get_random_object(self):
        """
        Return the most recently published post.
        """
        published_posts = Post.get_published_posts()
        r = random.randint(0, len(published_posts)-1)
        return Post.get_published_posts()[r]

    def get(self, request):
        """
        Redirect to the url of the most recently published post.
        """
        return HttpResponseRedirect(self.get_random_object().get_absolute_url())

class PostsView(generic.ListView):
    """
    A view that shows all published posts. 
    """
    template_name = 'gallery/posts.html'
    context_object_name = 'latest_post_list'
    
    def get_queryset(self):
        """
        Return all published posts (not including those set to be
        published in the future).
        """
        return Post.get_published_posts()

class DetailView(PostView):
    def get_queryset(self):
        """
        Return all posts, excluding any posts that aren't published yet.
        """
        return Post.get_published_posts()

apps/gallery/templates/gallery/base.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'gallery/style.css' %}">

{% block gallery-head %}
{% endblock %}

{% endblock %}

apps/gallery/templates/gallery/gallery.html
{% extends "gallery/base.html" %}

{% block title %}Galleri{% endblock %}

{% block menu %}
    <li></li>
    <li id="menu-latest"><a href="{% url 'gallery:latest' %}">Nyeste</a></li>
    <li id="menu-random"><a href="{% url 'gallery:random' %}">Tilfældig</a></li>
    <li></li>
{% endblock %}

{% block content %}

{% if latest_post_list %}
    <ul id="gallery-posts">
    {% for post in latest_post_list %}
    <li>
        <a href="{% url 'gallery:post' post.id %}">
            <img src="{{ post.image.url }}" title="{{ post.title }} af {{ post.author }}">
        </a>
    </li>
    {% endfor %}
    </ul>
{% else %}
    <p>Der er ingen tegninger.</p>
{% endif %}

{% endblock %}

apps/gallery/templates/gallery/index.html
{% extends "base.html" %}

{% block content %}

{% if latest_post_list %}
    <ul class="gallery_index">
    {% for post in latest_post_list %}
    <li class="index_post"><a href="{% url 'gallery:post' post.id %}">{{ post.title }} by {{ post.author }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock %}

apps/gallery/templates/gallery/post.html
{% extends "gallery/base.html" %}

{% block gallery-head %}
<script type="text/javascript">
    function leftArrowPressed() {
        {% with post.get_previous as p %} 
        {% if p %}
        window.location = "{% url 'gallery:post' p.pk %}";
        {% endif %}
        {% endwith %}
    }

    function rightArrowPressed() {
        {% with post.get_next as p %} 
        {% if p %}
        window.location = "{% url 'gallery:post' p.pk %}";
        {% endif %}
        {% endwith %}
    }

    document.onkeydown = function(evt) {
        evt = evt || window.event;
        switch (evt.keyCode) {
            case 37:
                leftArrowPressed();
                break;
            case 39:
                rightArrowPressed();
                break;
        }
    };
</script>
{% endblock %}

{% block title %}{{ post.title }} af {{ post.author }}{% endblock %}

{% block menu %}
    <li id="menu-prev">
        {% with post.get_previous as p %} 
        {% if p %}
        <a href="{% url 'gallery:post' p.pk %}">Forrige</a>
        {% else %}
        <p class="menu-passive">Forrige</p>
        {% endif %}
        {% endwith %}
    </li>
    <li id="menu-posts"><a href="{% url 'gallery:posts' %}">Arkiv</a></li>
    <li id="menu-random"><a href="{% url 'gallery:random' %}">Tilfældig</a></li>
    <li id="menu-next">
        {% with post.get_next as p %} 
        {% if p %}
        <a href="{% url 'gallery:post' p.pk %}">Næste</a>
        {% else %}
        <p class="menu-passive">Næste</p>
        {% endif %}
        {% endwith %}
    </li>
{% endblock %}

{% block content %}
<div id="post">
    <div id="post-header">
        <h1>{{ post.title }}</h1>
    </div>

    {% if post.image %}
    <img id="post-img" title="{{ post.title }} af {{ post.author }}" src="{{ post.image.url }}" />
    {% endif %}

    <div id="post-body">
        <div id="post-text">
            {{ post.text | safe }}
        </div>
        <p>{{ post.pub_date.date }}</p>
    </div>

    <div id="post-footer">
        <p>Lavet af {{ post.author }}</p>
    </div>
</div>
{% endblock %}

apps/gallery/templates/gallery/posts.html
{% extends "gallery/base.html" %}

{% block title %}Galleri{% endblock %}

{% block menu %}
    <li></li>
    <li id="menu-latest"><a href="{% url 'gallery:latest' %}">Nyeste</a></li>
    <li id="menu-random"><a href="{% url 'gallery:random' %}">Tilfældig</a></li>
    <li></li>
{% endblock %}

{% block content %}

{% if latest_post_list %}
    <ul id="gallery-posts">
    {% for post in latest_post_list %}
    <li>
        <a href="{% url 'gallery:post' post.id %}">
            <img src="{{ post.image.url }}" title="{{ post.title }} af {{ post.author }}">
        </a>
    </li>
    {% endfor %}
    </ul>
{% else %}
    <p>Der er ingen tegninger.</p>
{% endif %}

{% endblock %}

templates/base.html
<!DOCTYPE html>

{% load static %}

<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>{% block fulltitle %}{% block title %}Forside{% endblock %} - Løbefisk{% endblock %}</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block head %}{% endblock %}
</head>

<body>
<div id="background">
<div id="main">
    {% block header %}
    <div id="header">
        <a href="/"><img id="header-img" src="{% static 'images/header.png' %}"></a>
    </div>
    {% endblock %}

    <div id="menu">
        <div id="menu-list">
            <ul id="topnav">
            {% block menu %}
            {% endblock %}
            </ul>
        </div>
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>

    <div id="footer">
        <p>Copyright {% now 'Y' %}, Løbefisk.</p>
    </div>
</div>
</div>
</body>
</html>